In [1]:
#numpy most commonly used lib for data science

In [2]:
#numerical python also called array oriented computing written for scientific computation
#basic numpy object: n dim array
#n dim array: homogeneous array,list kinda

In [3]:
#all the values inside array should be of same data type 

In [4]:
#why numpy, fast(C PROG),convinience

In [5]:
import numpy


In [6]:
numpy.array([1,2,3])

array([1, 2, 3])

In [4]:
import numpy as np

In [10]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
b=np.array([1,2,3],[4,5,6])

TypeError: data type not understood

In [14]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b.shape

(2, 3)

In [17]:
a.shape

(3,)

In [18]:
b.dtype

dtype('int32')

In [19]:
b.ndim  #no. of row

2

In [21]:
print(type(a))

<class 'numpy.ndarray'>


In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
c=range(10000)


In [25]:
%timeit [i**3 for i in c]

6.51 ms ± 616 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
c_numpy=np.arange(10000)
%timeit c_numpy**3

32.7 µs ± 7.59 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [1]:
l1=range(10000)
l2=[i**2 for i in range(10000)]

In [2]:
%timeit list(map(lambda x,y: x*y, l1, l2))

2.54 ms ± 600 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
a1=np.array(l1)
b1=np.array(l2)

In [6]:
%timeit a1*b1

17.8 µs ± 1.96 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [12]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [16]:
np.full((3,3),2.2)

array([[2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2]])

In [17]:
np.full((3,3),2.2,dtype=np.int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [18]:
np.diag((1,2,3,4,5))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [19]:
v=np.array([1,2,3])

In [20]:
v

array([1, 2, 3])

In [21]:
np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [22]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [23]:
np.random.random()

0.9559829040476446

In [25]:
np.random.random()+2

2.65222099270934

In [27]:
np.random.random([3,3]) +2

array([[2.61850284, 2.90879272, 2.94818961],
       [2.48688511, 2.36813341, 2.93453592],
       [2.93874737, 2.08859431, 2.5218441 ]])

In [28]:
a=np.linspace(1,50,100)

In [29]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [30]:
a.itemsize

8

In [33]:
np.arange(18).shape

(18,)

In [34]:
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [35]:
b=np.arange(18).reshape(2,3,3)

In [36]:
b.shape

(2, 3, 3)

In [37]:
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [40]:
a=np.array([2,4,6,8,10,12,14,16,18])

In [41]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
a[0]

2

In [43]:
a[6]

14

In [44]:
a[2,4,6]

IndexError: too many indices for array

In [46]:
a[[2,4,6]]#bundle it,it is not list

array([ 6, 10, 14])

In [47]:
a[2:]

array([ 6,  8, 10, 12, 14, 16, 18])

In [48]:
a[2:5]

array([ 6,  8, 10])

In [49]:
a[0::2]

array([ 2,  6, 10, 14, 18])

In [51]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
a[2,2]

9

In [53]:
a>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [55]:
a[(a>2) & (a<5)]

array([3, 4])

In [56]:
a=np.arange(10)

In [57]:
b=a

In [58]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
b[0]=11

In [61]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [62]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [64]:
#pointing same location while allocating b to a

In [66]:
np.shares_memory(a,b)

True

In [67]:
a=np.arange(10)

In [68]:
b=a.copy()

In [69]:
b[0]=23

In [70]:
b

array([23,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [71]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.shares_memory(a,b)

False

In [76]:
a=np.array([[1,2,3],[4,5,6]])

In [81]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
transpose=a.T
transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
b=np.array([[7,8,9],[1,2,3,]])

In [87]:
a==b

array([[False, False, False],
       [False, False, False]])

In [88]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [89]:
np.hstack((a,b))

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 1, 2, 3]])

In [90]:
a=np.arange(1,10)

In [91]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [93]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [94]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [95]:
np.sum(a)

45

In [97]:
np.median(a)

5.0

In [98]:
np.mean(b)

5.0

In [99]:
np.std(a)

2.581988897471611

In [100]:
a=np.arange(1,10).reshape(3,3)

In [101]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
#determinant and inverse
np.linalg.det(a)

-9.51619735392994e-16

In [105]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [106]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [107]:
b=a.T

In [108]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [110]:
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [111]:
a=np.array([1,1,0],dtype=bool)

In [112]:
b=np.array([1,0,1],dtype=bool)

In [113]:
np.logical_or(a,b)

array([ True,  True,  True])

In [114]:
np.logical_and(a,b)

array([ True, False, False])

In [116]:
np.a==a

array([ True,  True,  True])

In [117]:
np.all(a==a)

True

In [119]:
a=np.array([[1,2],[3,4]])

In [120]:
a

array([[1, 2],
       [3, 4]])

In [121]:
a.sum(axis=0)

array([4, 6])

In [123]:
a.sum(axis=1)

array([3, 7])

In [124]:
a.max()

4

In [125]:
a.argmax()

3

In [126]:
a

array([[1, 2],
       [3, 4]])

In [127]:
a.shape

(2, 2)

In [130]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
a.shape

(10,)

In [132]:
a=np.arange(1,10)

In [133]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
a.shape

(9,)

In [136]:
a[:,np.newaxis].shape

(9, 1)

In [138]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])